blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/javilatte/optimia/discussions
    about: Ask questions, share ideas, or get help here.
  - name: Security Vulnerability
    url: https://github.com/javilatte/optimia/security/advisories/new
    about: Please report security vulnerabilities privately.
